/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { RequestOptionsBase } from "ms-rest-js";


/**
 * @interface
 * An interface representing IFormFile.
 */
export interface IFormFile {
  /**
   * @member {string} [contentType]
   */
  readonly contentType?: string;
  /**
   * @member {string} [contentDisposition]
   */
  readonly contentDisposition?: string;
  /**
   * @member {{ [propertyName: string]: string[] }} [headers]
   */
  readonly headers?: { [propertyName: string]: string[] };
  /**
   * @member {number} [length]
   */
  readonly length?: number;
  /**
   * @member {string} [name]
   */
  readonly name?: string;
  /**
   * @member {string} [fileName]
   */
  readonly fileName?: string;
}

/**
 * @interface
 * An interface representing Header.
 */
export interface Header {
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {string} [info]
   */
  info?: string;
  /**
   * @member {string} [comment]
   */
  comment?: string;
}

/**
 * @interface
 * An interface representing SDFileItem.
 */
export interface SDFileItem {
  /**
   * @member {Header} [header]
   */
  header?: Header;
  /**
   * @member {string} [cTab]
   */
  cTab?: string;
  /**
   * @member {string} [version]
   */
  version?: string;
  /**
   * @member {{ [propertyName: string]: string[] }} [properties]
   */
  properties?: { [propertyName: string]: string[] };
  /**
   * @member {string} [svg]
   */
  svg?: string;
}

/**
 * @interface
 * An interface representing TodoItem.
 */
export interface TodoItem {
  /**
   * @member {number} [id]
   */
  id?: number;
  /**
   * @member {string} [name]
   */
  name?: string;
  /**
   * @member {boolean} [isComplete]
   */
  isComplete?: boolean;
}

/**
 * @interface
 * An interface representing MyAPIApiTodoPostOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface MyAPIApiTodoPostOptionalParams extends RequestOptionsBase {
  /**
   * @member {TodoItem} [item]
   */
  item?: TodoItem;
}

/**
 * @interface
 * An interface representing MyAPIApiTodoByIdPutOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface MyAPIApiTodoByIdPutOptionalParams extends RequestOptionsBase {
  /**
   * @member {TodoItem} [item]
   */
  item?: TodoItem;
}

/**
 * @interface
 * An interface representing MyAPIApiValuesPostOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface MyAPIApiValuesPostOptionalParams extends RequestOptionsBase {
  /**
   * @member {string} [value]
   */
  value?: string;
}

/**
 * @interface
 * An interface representing MyAPIApiValuesByIdPutOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface MyAPIApiValuesByIdPutOptionalParams extends RequestOptionsBase {
  /**
   * @member {string} [value]
   */
  value?: string;
}
