/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


export const TodoItem = {
  required: false,
  serializedName: 'TodoItem',
  type: {
    name: 'Composite',
    className: 'TodoItem',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'Number'
        }
      },
      name: {
        required: false,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      isComplete: {
        required: false,
        serializedName: 'isComplete',
        type: {
          name: 'Boolean'
        }
      }
    }
  }
};

export const MyAPIApiTodoPostOptionalParams = {
  required: false,
  serializedName: 'ApiTodoPostOptions',
  type: {
    name: 'Composite',
    className: 'MyAPIApiTodoPostOptionalParams',
    modelProperties: {
      item: {
        required: false,
        serializedName: 'item',
        type: {
          name: 'Composite',
          className: 'TodoItem'
        }
      }
    }
  }
};

export const MyAPIApiTodoByIdPutOptionalParams = {
  required: false,
  serializedName: 'ApiTodoByIdPutOptions',
  type: {
    name: 'Composite',
    className: 'MyAPIApiTodoByIdPutOptionalParams',
    modelProperties: {
      item: {
        required: false,
        serializedName: 'item',
        type: {
          name: 'Composite',
          className: 'TodoItem'
        }
      }
    }
  }
};

export const MyAPIApiValuesPostOptionalParams = {
  required: false,
  serializedName: 'ApiValuesPostOptions',
  type: {
    name: 'Composite',
    className: 'MyAPIApiValuesPostOptionalParams',
    modelProperties: {
      value: {
        required: false,
        serializedName: 'value',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const MyAPIApiValuesByIdPutOptionalParams = {
  required: false,
  serializedName: 'ApiValuesByIdPutOptions',
  type: {
    name: 'Composite',
    className: 'MyAPIApiValuesByIdPutOptionalParams',
    modelProperties: {
      value: {
        required: false,
        serializedName: 'value',
        type: {
          name: 'String'
        }
      }
    }
  }
};
